[[redirects]]
  from = "/headers"
  to = "https://httpbin.org/headers"
  status = 200
  signed = "PROXY_REQUEST_KEY"


[[redirects]]
  from = "/get"
  to = "https://blossom-hip-ketch.glitch.me/get"
  status = 200
  signed = "PROXY_REQUEST_KEY"

[[redirects]]
  from = "/set"
  to = "https://blossom-hip-ketch.glitch.me/set"
  status = 200
  signed = "PROXY_REQUEST_KEY"

[[redirects]]
  from = "/ping"
  to = "https://ph.my.scribital.com/phoebe/v1/"
  status = 200
  signed = "PROXY_REQUEST_KEY"

[[redirects]]
  from = "/cb"
  to = "https://ph.my.scribital.com/phoebe/v1/oauth2/callback"
  status = 200
  signed = "PROXY_REQUEST_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PROXY_REQUEST_KEY = "blah-blah-blah-so-secret"
